export const TOKEN = 
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDEwN2UwOWFhMzk3MTIxODM4ZjI5MGEiLCJncm91cCI6Imdyb3VwLTExIiwiaWF0IjoxNjc4ODAyNDQ5LCJleHAiOjE3MTAzMzg0NDl9.a422X9TgA5kapDk2bPUxOGd9mYgMlW3am1R9RBKpXxU'

export const AUTH_DOG_TOKEN = 'auth_dog_token'
export const REDUX_STATE_SUBSCR = 'redux_state_subscr'
